### Create token
POST http://localhost:8080/v1/jwt-tokens

> {%
client.global.set("token", response.body.token);
 %}

### Verify token
GET http://localhost:8080/v1/jwt-tokens
Authorization: Bearer {{token}}

### Get self
GET http://localhost:8080/v1/self
x-jwt-claim-nested-claim: foo-bar

### Verify error, not bearer
GET http://localhost:8080/v1/jwt-tokens
Authorization: Bad

### Verify error, bad token
GET http://localhost:8080/v1/jwt-tokens
Authorization: Bearer bad

### Verify error, no authorization
GET http://localhost:8080/v1/jwt-tokens
