### Create token
POST http://localhost:8080/v1/jwt-tokens

> {%
client.global.set("token", response.body.token);
 %}

### Verify token
GET http://localhost:8080/v1/jwt-tokens
Authorization: Bearer {{token}}
